// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using BuscaPreciosV2.Models.Falabella;
//
//    var welcome = Welcome.FromJson(jsonString);

using System.Collections.Generic;

namespace BuscaPreciosV2.Models.Falabella
{
    public partial class ProductoResponse : Header
    {
        public string ComponentDomId { get; set; }
        public ControlParameter ControlParameter { get; set; }
        public string ComponentType { get; set; }
        public State State { get; set; }
        public TextDictionary TextDictionary { get; set; }
        public EndPoints EndPoints { get; set; }
    }

    public partial class ControlParameter
    {
        public bool EnableBankPromotions { get; set; }
        public bool EnableProductCompare { get; set; }
    }

    public partial class EndPoints
    {
        public AddCompareProduct GetSearchItemList { get; set; }
        public AddCompareProduct GetAssetMediaSet { get; set; }
        public AddCompareProduct AddCompareProduct { get; set; }
        public AddCompareProduct RemoveCompareProduct { get; set; }
        public AddCompareProduct AddToCart { get; set; }
    }

    public partial class AddCompareProduct
    {
        public string Name { get; set; }
        public string Type { get; set; }
        public string Path { get; set; }
    }

    public partial class State
    {
        public SearchItemList SearchItemList { get; set; }
        public string DescriptionText { get; set; }
        public string PrimaryLabel { get; set; }
    }

    public partial class SearchItemList
    {
        public long ResultsPerPage { get; set; }
        public long ResultsTotal { get; set; }
        public long PagesTotal { get; set; }
        public long CurentPage { get; set; }
        public bool UseRecordImage { get; set; }
        public List<ResultList> ResultList { get; set; }
        public List<Filter> Filters { get; set; }
        public List<GridView> SortBys { get; set; }
        public List<GridView> GridViews { get; set; }
        public SelectedRefinements SelectedRefinements { get; set; }
    }

    public partial class Filter
    {
        public string Name { get; set; }
        public string Type { get; set; }
        public string State { get; set; }
        public string Select { get; set; }
        public List<Value> Values { get; set; }
        public bool SearchIn { get; set; }
        public long DisplayingNumber { get; set; }
    }

    public partial class Value
    {
        public string Label { get; set; }
        public string PrimaryNav { get; set; }
        public bool Selected { get; set; }
        public string Url { get; set; }
        public long Count { get; set; }
    }

    public partial class GridView
    {
        public string Value { get; set; }
        public long? GridViewCode { get; set; }
        public bool Selected { get; set; }
        public string Label { get; set; }
        public string ExtraInfo { get; set; }
    }

    public partial class ResultList
    {
        public long ProductId { get; set; }
        public string Url { get; set; }
        public string Brand { get; set; }
        public string BackendCategory { get; set; }
        public long SkuId { get; set; }
        public bool IsPrimeAvailable { get; set; }
        public long MediaAssetId { get; set; }
        public string OnImageHover { get; set; }
        public string Title { get; set; }
        public bool UseImageAtProductLevel { get; set; }
        public List<Price> Prices { get; set; }
        public long Rating { get; set; }
        public long TotalReviews { get; set; }
        public bool IsCompare { get; set; }
        public bool IsCodAvailable { get; set; }
        public bool IsHdAvailable { get; set; }
        public bool IsCcAvailable { get; set; }
        public long AvailableSkusTotal { get; set; }
        public bool DisplayRatings { get; set; }
        public bool HasSize { get; set; }
        public bool Published { get; set; }
        public Specifications Specifications { get; set; }
        public MeatSticker MeatSticker { get; set; }
        public string Color { get; set; }
        public Variations Variations { get; set; }
    }

    public partial class MeatSticker
    {
        public First Second { get; set; }
        public First First { get; set; }
    }

    public partial class First
    {
        public string File { get; set; }
        public string Title { get; set; }
        public string ClassName { get; set; }
    }

    public partial class Price
    {
        public string Label { get; set; }
        public string OriginalPrice { get; set; }
        public string Symbol { get; set; }
        public long Type { get; set; }
        public bool IsLoyalty { get; set; }
        public bool OpportunidadUnica { get; set; }
    }

    public partial class Specifications
    {
        public string Modelo { get; set; }
        public string Tipo { get; set; }
        public string GarantADelProveedor { get; set; }
        public string Material { get; set; }
        public string Incluye { get; set; }
        public string Talla { get; set; }
        public string Disciplina { get; set; }
        public string Capacidad { get; set; }
        public string Color { get; set; }
        public string Marca { get; set; }
        public string HechoEn { get; set; }
        public string CapacidadLt { get; set; }
        public string Impermeable { get; set; }
        public string MaterialDeLaCarpa { get; set; }
        public string Alto { get; set; }
        public string Peso { get; set; }
        public string GNero { get; set; }
    }

    public partial class Variations
    {
        public List<GridView> Color { get; set; }
    }

    public partial class SelectedRefinements
    {
        public string ClearAllUrl { get; set; }
    }

    public partial class TextDictionary
    {
        public string CollectPointsText { get; set; }
        public string ClearCompareButton { get; set; }
        public string TitleSelectedFilters { get; set; }
        public string OfText { get; set; }
        public string PrepayText { get; set; }
        public string ViewPlansText { get; set; }
        public string GridViewText { get; set; }
        public string ShowMoreText { get; set; }
        public string DoneButtonText { get; set; }
        public string PrepayCta { get; set; }
        public string PlanText { get; set; }
        public string PlansText { get; set; }
        public string IsCodAvailableText { get; set; }
        public string Sortby { get; set; }
        public string CompareButton { get; set; }
        public string SortByText { get; set; }
        public string FromText { get; set; }
        public string ShowingText { get; set; }
        public string LeftNavigationTitleText { get; set; }
        public string CompareSubtitle { get; set; }
        public string OutOfStock { get; set; }
        public string EditLocation { get; set; }
        public string ViewText { get; set; }
        public string PlansCta { get; set; }
        public string ResultsText { get; set; }
        public string CompareBoxText { get; set; }
        public string ClearSelectedFilters { get; set; }
        public string AddToBasket { get; set; }
        public string AvailableForText { get; set; }
        public string TotalResultText { get; set; }
        public string AgotadoText { get; set; }
        public string PrimeLabelText { get; set; }
        public string ProductOutOfStockText { get; set; }
        public string CurrentPageResultText { get; set; }
    }


}
